spring.application.name=banking-app
server.port=${PORT:8080}

# ----------------------------------------
# PostgreSQL connection (UPDATED)
# ----------------------------------------
# Default Postgres port is 5432
# Neon Database Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ----------------------------------------
# JPA / Hibernate (UPDATED)
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Updated to PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ----------------------------------------
# Mail Server Host (SMTP)
# ----------------------------------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Protocol and Encoding
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

# JavaMail Specific Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ----------------------------------------
# JWT
# ----------------------------------------
jwt.expiration=86400000
jwt.secret=${JWT_SECRET}

# ----------------------------------------
# Spring Core Settings
# ----------------------------------------
spring.main.allow-circular-references=true
spring.jpa.open-in-view=false